Insert Into SqaJobs (  [Firstname] ,
    [Lastname] , 
    [Email]     ,
    [Addres]    ,
    [City]      ,
    [Stat]      ,
    [Postal]    ,
    [Phone]    ,
    [Resum]     ,
    [Sal]       ,
    [Interest]  ) Values('Laiba','Riaz','laibariaz0@gmail.com','House no. 72,Ashraf Garden','Raiwind','Punjab','55610','03216708300','C:\\Users\\Admin\\Downloads\\bug.doc','500','Hi,I am an automation engineer')